#!/usr/bin/env bash

readonly User="build"

set -o nounset # Stop when there are undefined variables.

pacman -Syu --noconfirm

mkdir -p "/home/${User}/"
chown -R "${User}:${User}" "/home/${User}/"

sudo -u "${User}" ./simple "${@}"

cd /home/build/.local/share/rua/checked_tars/
mv /home/build/.local/share/rua/checked_tars/*/*pkg.tar.xz .
find . -type d -delete
repo-add "custom.db.tar.gz" ./*.pkg.tar.xz
