#!/usr/bin/env bash

readonly Command="${1:-""}"

if [[ -z "${Command}" ]]; then
	echo "need command (arg 1)" >&2
	exit 1
fi

shift

case "${Command}" in
"keys")
	./keys "${@}"
	;;

"build")
	./build "${@}"
	;;

"clean")
	./clean "${@}"
	;;

"setup")
	./setup "${@}"
	;;

*)
	echo "unkown command ${Command}" >&2
	exit 1
	;;
esac
