#!/usr/bin/env bash

set -o nounset   # Stop when there are undefined variables.

readonly User="build"

mkdir -p "/home/${User}/.gnupg"
chown -R "${User}:${User}" "/home/${User}/.gnupg"
chmod 700 "/home/${User}/.gnupg"

for key in "${@}"; do
  for server in $(shuf -e \
    hkp://p80.pool.sks-keyservers.net:80 \
    keyserver.ubuntu.com \
    hkp://keyserver.ubuntu.com:80 \
    keyserver.pgp.com \
    pgp.mit.edu) ; do \

    sudo -u "${User}" gpg --keyserver "${server}" --recv-keys "${key}" && break || : ; \
  done; \
done
