#!/usr/bin/env bash

set -o nounset # Stop when there are undefined variables.

rsync -azzPhe ssh \
	"${HOME}/.cache/custom_archlinux_thaller_ws/outdir/build/.local/share/rua/checked_tars/" \
	'192.168.1.200:/data/archlinux_thaller_ws/custom/' \
	--delete

ssh root.thaller.ws 'varnishadm "ban req.http.host ~ custom-archlinux.thaller.ws"'
