#!/usr/bin/env bash

set -o errexit  # Stop on command failures.
set -o errtrace # Make sure any error trap is inherited.
set -o nounset  # Stop when there are undefined variables.
set -o pipefail # Stop when a command in a pipe failes.

ScriptPath="$(
  cd -- "$(dirname "$0")" >/dev/null 2>&1
  pwd -P
)"
readonly ScriptPath

readonly Package="${1:?Package name is required.}"

if [[ -f "${ScriptPath}/Dockerfile.${Package}" ]]; then
  cat "${ScriptPath}/Dockerfile.${Package}"
else
  cat <<EOF
FROM builder AS ${Package}
RUN git clone "https://aur.archlinux.org/${Package}.git" && \\
  cd "${Package}" && \\
  makepkg --syncdeps --noconfirm --clean --skippgpcheck && \\
  cp *.pkg.tar.zst /output

EOF
fi
