#!/usr/bin/env bash

set -o errexit  # Stop on command failures.
set -o errtrace # Make sure any error trap is inherited.
set -o nounset  # Stop when there are undefined variables.
set -o pipefail # Stop when a command in a pipe failes.

ScriptPath="$(
  cd -- "$(dirname "$0")" >/dev/null 2>&1
  pwd -P
)"
readonly ScriptPath

while read package; do
  if [[ -f "${ScriptPath}/Dockerfile.${package}" ]]; then
    cat "${ScriptPath}/Dockerfile.${package}"
  else
    cat <<EOF
FROM builder as ${package}

RUN git clone "https://aur.archlinux.org/${package}.git" && \\
  cd "${package}" && \\
  makepkg \\
  --syncdeps \\
  -sc \\
  --noconfirm && \\
  ls -lah && \\
  cp *.pkg.tar.* /output && \\
  cd .. && \\
  rm -rf "${package}"
EOF
  fi
done <packages.list

echo

echo 'FROM builder'

while read package; do
  echo "COPY --from=${package} /output /output"
done <packages.list

echo 'ENTRYPOINT [ "sleep", "infinity" ]'
